name: openfortivpn-thementor # you probably want to 'snapcraft register <name>'
version: '1.4.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: Open source fortinet SSL VPN Client # 79 char long summary
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: classic # use 'strict' once you have the right plugs and slots

apps:
  openfortivpn:
    command: openfortivpn

parts:
  openfortivpn:
    plugin: autotools
    stage-packages:
      - libssl 
      - openssl
      - ppp
    build-packages:
      - gcc 
      - automake 
      - autoconf 
      - libssl-dev
