name: openfortivpn-thementor # you probably want to 'snapcraft register <name>'
version: '1.4.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: Open Source Fortinet SSL VPN Client # 79 char long summary
description: |
  openfortivpn is a client for PPP+SSL VPN tunnel services.
  It spawns a pppd process and operates the communication between the gateway and this process.

  It is compatible with Fortinet VPNs.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  openfortivpn:
    command: openfortivpn
    plugs:
      - network
      - network-bind
      - ppp
      - network-control
      - firewall-control
      - bluetooth-control
parts:
  openfortivpn:
    plugin: autotools
    stage-packages:
      - openssl
      - ppp
    build-packages:
      - gcc 
      - automake 
      - autoconf 
      - libssl-dev
      - pkg-config
    install: |
      ./autogen.sh
      ./configure --prefix=/usr/local --sysconfdir=/etc
